# Generated by Django 2.2.16 on 2021-10-13 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211013_0702'),
        ('users', '0003_auto_20211013_1023'),
    ]

    operations = [
    ]
