# Generated by Django 2.2.16 on 2021-10-14 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='genre',
        ),
    ]
