# Generated by Django 2.2.16 on 2021-10-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0004_title_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(related_name='titles', to='titles.Genre'),
        ),
    ]
