# Generated by Django 2.2.16 on 2021-10-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0005_auto_20211014_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
